#!/usr/bin/env python3
"""Generate R8-observed.txt with EVERY quoted range DERIVED from the runs captured in the
same execution.

This exists because of a real, twice-repeated failure: R7, and then R8 one commit after
R7 was fixed, both shipped an artifact whose prose quoted one run set while its own pinned
raw block held another. Hand-copying numbers from a previous run into prose is the defect;
"be more careful" is not a fix. Here the raw block and the prose come from the SAME
subprocess output, so they cannot disagree.

Usage:  python3 r8_report.py > R8-observed.txt
"""
import re, subprocess, os, statistics

HERE = os.path.dirname(os.path.abspath(__file__))
JAVA = "/opt/jdks/jdk-27/bin/java"
NDLIB = os.path.join(HERE, "r8-ndarray/target/release/libr8_ndarray.so")


def run(cmd):
    out = subprocess.run(cmd, capture_output=True, text=True, cwd=HERE).stdout
    return "\n".join(l for l in out.splitlines() if "JAVA_TOOL" not in l)


def rng(vals, fmt="{:.0f}"):
    """Observed range, never a single-run pin."""
    lo, hi = min(vals), max(vals)
    return fmt.format(lo) if lo == hi else f"{fmt.format(lo)}-{fmt.format(hi)}"


standalone = run(["./r8_standalone"])
jvm = run([JAVA, "--enable-preview", "--enable-native-access=ALL-UNNAMED",
           f"-Dr8.lib={HERE}/libr8_native.so", f"-Dr8.ndlib={NDLIB}",
           "-cp", "/tmp/r45out", "R8_EntropyBoundary"])

# ── parse: every number below comes from the text printed above ──
arms, checks = {}, {}
for line in jvm.splitlines():
    m = re.match(r"^([ABCDE]'?)\s+([\d,]+)\s+([\d.]+)\s+([\d.]+)\s+(-?\d+)", line)
    if m:
        arm, _, secs, mops, chk = m.groups()
        arms.setdefault(arm, {"s": [], "m": []})
        arms[arm]["s"].append(float(secs)); arms[arm]["m"].append(float(mops))
        checks.setdefault(arm, set()).add(int(chk))

sa = [float(x) for x in re.findall(r"([\d.]+) M ops/s", standalone)]
sa_chk = {int(x) for x in re.findall(r"checksum (-?\d+)", standalone)}
scan_ms = float(re.search(r"partition scan ([\d.]+) ms", jvm).group(1))
mask_ms = float(re.search(r"mask build .*?: ([\d.]+) ms", jvm).group(1))
ops2 = int(re.search(r"target=([\d,]+)", jvm).group(1).replace(",", ""))
ops_pass = int(re.search(r"opsPerPass=(\d+)", jvm).group(1))

med = {a: statistics.median(v["m"]) for a, v in arms.items()}
meds = {a: statistics.median(v["s"]) * 1000 for a, v in arms.items()}
sD2, sE2 = meds["D'"], meds["E'"]
b_pass = ops_pass / (med["B'"] * 1e6) * 1e3
e_pass = ops_pass / (med["E'"] * 1e6) * 1e3
d_pass = ops_pass / (med["D'"] * 1e6) * 1e3
save = b_pass - e_pass
be_mask, be_scan = mask_ms / save, scan_ms / save
d_e2e, e_e2e = scan_ms + sD2, mask_ms + sE2

P = print
P(f"JDK: {run([JAVA, '--version']).splitlines()[0]}")
P(f"rustc: {run(['rustup', 'run', '1.97.1', 'rustc', '--version'])} -- ALL Rust artifacts")
P("  (native kernels, standalone baseline AND the ndarray crate: one compiler, one profile:")
P("   -O -Ctarget-cpu=x86-64-v4 -Cdebuginfo=0. Unified on operator review so the")
P("   'bulk FFI == standalone' claim has no toolchain escape hatch.)")
P("  target-cpu v4: host has avx512f/bw/dq/vl/vbmi/ifma. ndarray's own .cargo/config.toml")
P("  pins v3; this crate sits outside it, so v4 is explicit -- that is what makes simd.rs")
P("  dispatch to the simd_avx512 arm.")
P("")
P("THIS FILE IS GENERATED by r8_report.py. Every range in the READING sections is derived")
P("from the raw runs printed below it, in the same execution. Do not hand-edit numbers:")
P("R7, and then R8 one commit later, both shipped prose quoting a different run set than")
P("their own pinned block. Regenerate instead.")
P("")
P("=== rust standalone baseline (no JVM in the process) ===")
P(standalone)
P("")
P("=== five arms, one JVM process, ONE native fill authority for every arm ===")
P(jvm)
P("")
P("SYMMETRY PROOF")
part1 = set().union(*(checks[a] for a in ("A", "B", "D"))) | sa_chk
part2 = set().union(*(checks[a] for a in ("A'", "B'", "D'", "E'")))
P(f"  part 1: A, B, D and the standalone Rust PROCESS all report {part1.pop()}"
  f" ({'IDENTICAL' if not part1 else 'DIVERGENT -- INVESTIGATE'}).")
P(f"  part 2: A', B', D', E' all report {part2.pop()}"
  f" ({'IDENTICAL' if not part2 else 'DIVERGENT -- INVESTIGATE'}).")
P("  Same bytes, same op multiset, every arm. C's checksum is its 1e8-op prefix,")
P("  cross-checked exactly against the Java sweep at the same op count (printed above).")
P("  Arm E additionally asserts its mask popcounts equal the Java partition scan's counts,")
P("  so the two population representations are provably the same SET, not merely the same size.")
P("")
P("READING -- PART 1 (period-4 classid, r & 3): THE CONTROL")
P(f"  B  bulk FFI -> generic Rust   {rng(arms['B']['m'])} M ops/s vs standalone {rng(sa)}")
# Calibrated claim (operator review): assert only what the comparison supports. When the
# in-JVM arm is FASTER than the standalone process -- which has been observed -- the two
# cannot be called performance-identical; process/JIT/turbo/cache context is demonstrably
# larger than any crossing cost. What survives either way is that no penalty is exposed.
sa_med = statistics.median(sa)
if med["B"] > max(sa):
    P(f"     NOTE: the in-JVM arm is FASTER than the standalone process here"
      f" ({med['B']/sa_med:.2f}x median). The two are therefore NOT performance-identical --")
    P("     process/JIT/turbo/cache context dominates any crossing cost at this scale.")
elif med["B"] < min(sa):
    P(f"     NOTE: the in-JVM arm is slower here ({med['B']/sa_med:.2f}x median); check whether"
      " that gap exceeds the observed run-to-run spread before attributing it to the crossing.")
else:
    P("     The two arms' observed ranges overlap.")
P("     -> ONE BULK PANAMA CROSSING SHOWS NO MEASURABLE PENALTY AT THIS SCALE.")
P("        (Deliberately NOT 'bulk FFI equals standalone Rust' -- see the note above.)")
P(f"  D  monomorphic kernels        {rng(arms['D']['m'])} M ops/s"
  f" -- {'D > B FALSIFIED' if med['D'] <= med['B'] else 'D > B holds'} here.")
P("     A period-4 pattern is perfectly branch-predictable, so the generic sweep's per-row")
P("     dispatch is already free; specialization cannot beat a predictor that specialized.")
P(f"  A  Java in-process            {rng(arms['A']['m'])} M ops/s"
  f" (~{med['B']/med['A']:.0f}x behind Rust, same loop)")
P(f"  C  FFI PER PROJECTION         {rng(arms['C']['m'])} M ops/s"
  f" = ~{1000/med['C']:.1f} ns/op, ~{med['B']/med['C']:.0f}x slower than B.")
P("     The anti-JNI rule, quantified.")
P("")
A2, B2, D2, E2 = arms["A'"], arms["B'"], arms["D'"], arms["E'"]
mA2, mB2, mD2, mE2 = med["A'"], med["B'"], med["D'"], med["E'"]
P("READING -- PART 2 (random classid, SplitMix64): WHERE DISPATCH ACTUALLY COSTS")
P(f"  A'  Java                       {rng(A2['m'])} M ops/s")
P(f"  B'  generic Rust, per-row match {rng(B2['m'])} M ops/s"
  f" -- a {med['B']/mB2:.1f}x COLLAPSE from part 1.")
P("      The dispatch cost was always there; the branch predictor was paying it.")
P(f"  D'  index-list partition -> mono kernels {rng(D2['m'])} M ops/s"
  f" ({mD2/mB2:.2f}x B')")
P(f"  E'  ndarray::simd masks -> mask sweep    {rng(E2['m'])} M ops/s"
  f" ({mE2/mB2:.2f}x B')")
P("")
P("THE FINDING")
P(f"  Under a distribution where dispatch actually costs, the split architecture wins"
  f" ~{mE2/mB2:.1f}x")
P("  -- the selector layer (classid -> ClassView -> mask) creates the information ONCE,")
P("  before the sweep, where the monolithic generic loop re-derives it per row and eats")
P("  the mispredict every time.")
P("")
P("  THE COMPARISON THAT MATTERS IS END-TO-END, NOT SWEEP-ONLY (operator correction).")
P("  D' and E' sweeps are effectively tied, so quoting E' as '2-3% slower' understates it.")
P("  What differs is BUILDING the population, and that must be counted:")
P(f"      D' = build {scan_ms:6.2f} ms (Java scalar scan -> index lists) + sweep {sD2:6.1f} ms"
  f" = {d_e2e:6.1f} ms")
P(f"      E' = build {mask_ms:6.2f} ms (ndarray::simd, ONE bulk call)   + sweep {sE2:6.1f} ms"
  f" = {e_e2e:6.1f} ms")
P(f"    -> the lawful mask pipeline wins END-TO-END by {(d_e2e/e_e2e-1)*100:.0f}% on the FIRST"
  f" execution ({scan_ms/mask_ms:.1f}x cheaper to build),")
P("       and leaves behind a MASK -- reusable for and/or/andnot, authorization, traversal,")
P("       attention -- where D' leaves an index list that is a materialized population the")
P("       mask-native law forbids as internal currency.")
P("")
P("  Amortization terms:")
P(f"      B' {b_pass:.4f} ms/pass; D' {d_pass:.4f}; E' {e_pass:.4f} -> saving {save:.4f} ms/pass vs B'")
P(f"      break-even for the {mask_ms:.2f} ms mask build : ~{be_mask:.0f} passes")
P(f"      break-even for the {scan_ms:.2f} ms Java scan  : ~{be_scan:.0f} passes")
P("")
P("WHAT THIS DOES AND DOES NOT SHOW")
P("  - NOT 'Java is faster than Rust'. The winning kernels ARE Rust; the masks are built by")
P("    Rust (ndarray::simd). A Rust-alone program that built masks first would match E'.")
P("    The win is specialization PLACEMENT, not language.")
P("  - What IS architectural: the knowledge lives in the classid/ClassView layer, the")
P("    population stays a mask, the sweep is one bulk call over it -- the mask-native")
P("    execution shape the workspace law already specifies, now with a measured reason.")
P("  - Part 1 is the control that keeps part 2 honest: when dispatch is predictable,")
P("    partitioning buys NOTHING. Entropy reduction pays exactly when there is entropy.")
P("")
P("STABILITY")
P("  Every figure above is an observed range or a median over the raw runs printed in this")
P(f"  same file. Java arms spread up to {max(max(v['m'])/min(v['m']) for k,v in arms.items() if k.startswith('A')):.1f}x"
  f" run-to-run; Rust-kernel arms a few percent.")
